# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "L3StSLKCMn0nzLcEWrqElkYRAI84PiOiZursBriDLQ8d3TuQldruzKLiBXdqFmn31LazUiFy5K2tRImPSyjj+hTQPCx7zkRzllWuBs9jd+ox9QGejRAks7al3Gf6SpxMAaiDYv5nPB+bORagbKld3ncsOQ8TRtaRyh9f0NJFI46IM6Aoz/jGj1vRPNk6IhvLyU/L3NsFww1kFla/9fNm7OhcpyWk1L86i+OW4yat18XoZTdEceanImRm1AVLs+9TeI/hTudZffs1bJuG1HzB4um5ULpyf9ZFVBipDOkk95cE9BlFHaxY+G8BDjK/hLFVXE7iE6Y47iApYpBjxvHlp+D02wCym4C6+t94x95sjJ6LBc5CTYWrDzecwOgdGRX6hBVLqWiqkehlgEATWb42AocjoQNH+8YSS0PgAA4Vg7812mr+Xb4vuCK/1D1gw5SFSfKAAfBg1T0cdhpsH0bqghS2z7FA/q+pMd09VmfIr5OvT73k/Hz3Yxkw4W9x19T98g9H82oEfsVfd3ZyujwhuBdoYn3550J/g8FXty4iZ/4I0d11s9Juk3a+4bI4D5VXDnL2AbhszjAuyTAZ3Vorx+PfXOEUHGcYBjiPoYyxzV415lBxlRMS1CxaB/nwcyWsJ9mNM4nmD6ZFmv662dkoWlc3Xceqb/Go1c6HjduwfPg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
