travis:
  secure:
    BINSTAR_TOKEN: L3StSLKCMn0nzLcEWrqElkYRAI84PiOiZursBriDLQ8d3TuQldruzKLiBXdqFmn31LazUiFy5K2tRImPSyjj+hTQPCx7zkRzllWuBs9jd+ox9QGejRAks7al3Gf6SpxMAaiDYv5nPB+bORagbKld3ncsOQ8TRtaRyh9f0NJFI46IM6Aoz/jGj1vRPNk6IhvLyU/L3NsFww1kFla/9fNm7OhcpyWk1L86i+OW4yat18XoZTdEceanImRm1AVLs+9TeI/hTudZffs1bJuG1HzB4um5ULpyf9ZFVBipDOkk95cE9BlFHaxY+G8BDjK/hLFVXE7iE6Y47iApYpBjxvHlp+D02wCym4C6+t94x95sjJ6LBc5CTYWrDzecwOgdGRX6hBVLqWiqkehlgEATWb42AocjoQNH+8YSS0PgAA4Vg7812mr+Xb4vuCK/1D1gw5SFSfKAAfBg1T0cdhpsH0bqghS2z7FA/q+pMd09VmfIr5OvT73k/Hz3Yxkw4W9x19T98g9H82oEfsVfd3ZyujwhuBdoYn3550J/g8FXty4iZ/4I0d11s9Juk3a+4bI4D5VXDnL2AbhszjAuyTAZ3Vorx+PfXOEUHGcYBjiPoYyxzV415lBxlRMS1CxaB/nwcyWsJ9mNM4nmD6ZFmv662dkoWlc3Xceqb/Go1c6HjduwfPg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
